### ISSUE TITLE
Bug: Python error 

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/CIN-validator#446]
**Describe the bug**
Trying to validate in Front-End (after latest release on 3 May) returns SSL and python errors:

![image](https://user-images.githubusercontent.com/89449804/236415349-c9f03493-e00d-463a-9dd8-de86580b87e9.png)

**Comment by tab1tha** [comment]
Oh sorry about that @SLornieCYC 
I'll have a look

**Comment by tab1tha** [comment]
This will be fixed by this wheel update https://github.com/data-to-insight/cin-validator-fe/pull/139

The error was caused because[ this change](https://github.com/data-to-insight/CIN-validator/commit/c7af587dd436f9ab378428a88d396c2537e7fd9e) had not yet been compiled into the backend. So I've recompiled the backend and updated the wheel file.

**Comment by tab1tha** [comment]
This seems fixed now.

Replication:
I ran the `fake_CIN_census_2021.xml` file and only choose `rule 100` such that no `la issues` are found. The python error that was raised before the update is no longer being raised.

**Comment by SLornieCYC** [comment]
Working for me too!  I've put the SSL issue in a separate issue (#447) as unrelated to this script error.
